# Generated by Django 4.2.8 on 2023-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=100, verbose_name='Пассопрт')),
                ('address', models.CharField(max_length=250, verbose_name='Адресс')),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
