# Generated by Django 4.2.8 on 2023-12-15 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, verbose_name='Категория')),
                ('time_active', models.IntegerField(blank=True, null=True, verbose_name='Время действия')),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Treatys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treaty.categories')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
