# Generated by Django 4.2.8 on 2023-12-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('treaty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatys',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user'),
        ),
    ]
